language: java
install: mvn -B clean
script: "mvn install -B -DreuseForks=false -Dnet.sf.expectit.TestUtils.smallTimeout=500 -Dnet.sf.expectit.TestUtils.longTimeout=2000"
jdk:
  - oraclejdk8
  - openjdk7
after_success:
  - mvn clean cobertura:cobertura -DskipAnalysis
  - mvn -N coveralls:cobertura
secure: "lB8woHPPDJ7mLznb/xgPNENPr6jrcRaU21DKyihgz0gc+4wFnCdE1aTQzSqfCzlnKeipmJNtgoDPCNy/UWRqzkDipMVoCL1xlhMPu07qno4FGSGovRIAUtQyhOFRnGpR975j+FLi9/Ohg+0Du/cqsYg/5uyIXoSISGQc0Ce/9A0="
